name: Docker build, publish and deploy


on:
  push:

  workflow_dispatch:
    inputs:
      docker_label:
        description: 'Docker image will be pushed to edulint/edulint-web-frontend:<docker_label>. For deploy to dev server use tag dev.'
        required: true
        default: 'latest'

env:
  docker_label: "${{ inputs.docker_label || github.ref == 'refs/heads/main' && 'latest' || 'dev' }}"
  TARGET_FOLDER: "${{ github.ref == 'refs/heads/main' && secrets.SSH_PROD_FOLDER || secrets.SSH_DEV_FOLDER }}"
  edulint_web_ref: "${{ github.ref == 'refs/heads/main' && 'main' || 'dev' }}"

jobs:

  redeploy-full-stack:
    uses: GiraffeReversed/edulint-web/.github/workflows/deploy.yaml@dev
    secrets: inherit



