name: Docker build, publish and deploy


on:
  push:

  workflow_dispatch:
    inputs:
      docker_label:
        description: 'Docker image will be pushed to edulint/edulint-web-frontend:<docker_label>. For deploy to dev server use tag dev.'
        required: true
        default: 'latest'

env:
  docker_label: "${{ inputs.docker_label || github.ref == 'refs/heads/main' && 'latest' || 'dev' }}"
  target_folder: "${{ github.ref == 'refs/heads/main' && secrets.SSH_PROD_FOLDER || secrets.SSH_DEV_FOLDER }}"
  edulint_web_ref: "${{ github.ref == 'refs/heads/main' && 'main' || 'dev' }}"

jobs:

  redeploy-full-stack:
    uses: GiraffeReversed/edulint-web/.github/workflows/deploy.yaml@dev
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PROD_FOLDER: ""
      SSH_DEV_FOLDER: ""
    with:
      TARGET_FOLDER: ${{ env.target_folder }}
      BRANCH: "dev"  # github.ref_name



